### PR TITLE
fix: #204 UI Redesign - Desktop - Navigation Menu

### LINKED ISSUE #204: UI Redesign - Desktop - Navigation Menu
**Description**
The task is to implement the new design for the navigation menu in the desktop app.

**Assets and Design Screens** 
All assets and design screens have already been created.
- The Figma design can be found here  https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=1%3A2
- The Assets required can be found here https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=0%3A1

For help with using Figma please watch this short tutorial video
https://user-images.githubusercontent.com/69275762/192322842-2ac40f88-c396-4a66-933b-3c8abae516c3.mov

**Additional context**
- This work should be done on the UI_Redesign branch https://github.com/atsign-foundation/atmosphere_pro/tree/ui_redesign

### PR DESCRIPTION
**Pull request by ketanvishwakarma**
**- What I did**
- fixed #204 

**- How I did it**
- Added new "Inter" fonts, as well as new text styles.
- Image assets have been added/updated.
- Replaced Avatar widgets with new widgets that have "V2" as a suffix to avoid breaking existing code.
- Added gradient (orange/yellow) sidebar button
- Navigation menu has been updated

**- How to verify it**
- You just need to do a login to see Home screen that contains navigation menu 

**- Description for the changelog**
- Updated fonts and navigation menu and changed location of the user avatar to navigation menu

### CODE REVIEW

**Comment by tinashe404** [comment]
The UI changes look great! @nitesh could you please do a code review on this?

**Comment by tinashe404** [comment]
@sachins-geekyants Could you please do a code review on this?

**Comment by nitesh2599** [comment]
@tinashe404 Sorry for the delay, the code looks fine to be merged.

**Comment by tinashe404** [comment]
@ketanvishwakarma thanks! This PR may qualify for an atSign giftcard. Please forward a copy of your PR approval email to hacktoberfest@atsign.com and we will reach out if you are a winner.

**Pull request merged**
