### PR TITLE
feat: history screen new UI

### PR DESCRIPTION
**Pull request by Sardar1208**
**- What I did - added new UI for history screen**
ticket link - https://github.com/atsign-foundation/atmosphere_pro/issues/294

### CODE REVIEW

**Comment by sonle-geekyants** [comment]
@Sardar1208 I have faced the issues when I sent a file the history was duplicated (3 times) and after reloading the app, the sent history disappeared.

https://github.com/atsign-foundation/atmosphere_pro/assets/88494375/71b1ff8c-6558-40cd-88f6-660d3e59c674

**Comment by Sardar1208** [comment]
> @Sardar1208 I have faced the issues when I sent a file the history was duplicated (3 times) and after reloading the app, the sent history disappeared.
> 
>  sent_history_bug.mp4

@sonle-geekyants Is this happening every time? I just tested it and its working fine for me. 
Also, I have now added a fix that prevents clicking the send button multiple times and show appropriate message in this pr - https://github.com/atsign-foundation/atmosphere_pro/pull/306

So if this issue is happening if the file is set multiple times then the above Pr should prevent it

**Comment by sonle-geekyants** [comment]
> > @Sardar1208 I have faced the issues when I sent a file the history was duplicated (3 times) and after reloading the app, the sent history disappeared.
> > sent_history_bug.mp4
> 
> @sonle-geekyants Is this happening every time? I just tested it and its working fine for me. Also, I have now added a fix that prevents clicking the send button multiple times and show appropriate message in this pr - #306
> 
> So if this issue is happening if the file is set multiple times then the above Pr should prevent it

@Sardar1208 The bugs have gone for now but the issue of clicking send button multiple times is still remaining so please check again

**Comment by Sardar1208** [comment]
> > > @Sardar1208 I have faced the issues when I sent a file the history was duplicated (3 times) and after reloading the app, the sent history disappeared.
> > > sent_history_bug.mp4
> > 
> > 
> > @sonle-geekyants Is this happening every time? I just tested it and its working fine for me. Also, I have now added a fix that prevents clicking the send button multiple times and show appropriate message in this pr - #306
> > So if this issue is happening if the file is set multiple times then the above Pr should prevent it
> 
> @Sardar1208 The bugs have gone for now but the issue of clicking send button multiple times is still remaining so please check again

@Son This issue is fixed in PR that I mentioned in above comment. Once everything is merged it will work fine

**Review by sonle-geekyants — APPROVED** [review]

**Pull request merged**
