### PR TITLE
feat: #205 UI Redesign - Mobile - Navigation Menu

### PR DESCRIPTION
**Pull request by AdiAr11**
**- What I did**
implemented the bottom navigation bar, #205 

**- How I did it**
I created a custom navigation bar, added all the necessary svg files and made it work.

**- How to verify it**
open the app and in the bottom you will see the new bottom navigation bar.

**- Description for the changelog**

### CODE REVIEW

**Comment by tinashe404** [comment]
This is a great start. Some minor changes that are needed:
- The icons are moving slightly when clicked on. They should all remain in the same position
- The Contacts icon should go to the Contacts Screen
- The Home icon in the middle should go to the home screen which is currently the one that shows "Welcome @tinashe404 select a file......."

**Comment by AdiAr11** [comment]
Hi @tinashe404 , I've made the required changes.

**Comment by tinashe404** [comment]
@AdiAr11 the icons are still moving when clicked. They should remain in the same position at all times. See video...

https://user-images.githubusercontent.com/69275762/195637276-285c4a99-cdb5-47f4-8063-b93ea46d90c6.mov

**Comment by ksanty** [comment]
@AdiAr11 I also checked as well and found the following:

- [ ] Back arrow on contacts and my files backs to a black void screen
- [ ] Safe area at bottom of the nav bar is missing
- [ ] Settings is not the correct screen (@tinashe404 not sure where to direct @AdiAr11)
- [ ] Back button for history is not operational

**Comment by ksanty** [comment]
@AdiAr11 I also checked as well and found the following:

- [ ] Back arrow on contacts and my files backs to a black void screen
- [ ] Safe area at bottom of the nav bar is missing
- [ ] Settings is not the correct screen (@tinashe404 not sure where to direct @AdiAr11)
- [ ] Back button for history is not operational

**Comment by AdiAr11** [comment]
@tinashe404 I'll do something so they don't move. To accommodate all three things, they are moving. I'll reduce the size if i can.
@ksanty The safe area is implemented. I have adjusted it in the other issue Im working on, so it looks like the figma design. The other issue you are talking about I think can be new issue. Here i just implemented the navigation bar. If you want you can create those issue and assign me.
Also a few screens are not developed yet, like the settings screen which are assigned to someone else. When they complete those, only one line of code needs to be changed to redirect user to the required screen.

**Comment by AdiAr11** [comment]
https://user-images.githubusercontent.com/54585121/195983596-b734e0fa-3ccd-45f0-b4bf-49713ceafcae.mp4

Hi @tinashe404 I've made the changes so the icons don't move now.

**Comment by tinashe404** [comment]
@AdiAr11 could you please try on a 12pro Max simulator? The icons are still moving...
https://user-images.githubusercontent.com/69275762/196463106-2be0a763-b7fb-4bd6-9902-fc99aea1c006.mov

**Comment by AdiAr11** [comment]
sure, i'll try it on 12 pro max simulator!

**Comment by AdiAr11** [comment]
Hi @tinashe404 , I just ran the app on iphone 12 pro max and the navigation bar works fine. Maybe you didn't take the latest pull from my branch. Could you please check again? I'll attach the screen recording for iphone 12 pro max as well. Thank you

https://user-images.githubusercontent.com/54585121/197729580-c6170a38-e720-4073-9bcf-ed241b4d030e.mp4

**Comment by tinashe404** [comment]
@AdiAr11 This looks great! The settings page has been implemented and merged to the redesign branch, could you pull that  in and point the settings icon to that. once you've done that, @nitesh2599 or @sachins-geekyants will do a code review!

**Comment by AdiAr11** [comment]
@tinashe404 sure, i'll do that.

**Comment by AdiAr11** [comment]
@tinashe404 I am done with the changes!

**Comment by nitesh2599** [comment]
@tinashe404 The code looks fine to be merged.

**Comment by tinashe404** [comment]
@AdiAr11 thanks! This PR may qualify for an atSign giftcard. Please forward a copy of your PR approval email to hacktoberfest@atsign.com and we will reach out if you are a winner.

**Comment by AdiAr11** [comment]
> @AdiAr11 thanks! This PR may qualify for an atSign giftcard. Please forward a copy of your PR approval email to hacktoberfest@atsign.com and we will reach out if you are a winner.

Thank you @tinashe404 . Just forwarded the email.

**Pull request merged**
