### PR TITLE
feat: #211 UI Redesign - Desktop - Settings

### LINKED ISSUE #211: UI Redesign - Desktop - Settings
**Description**
The task is to implement the new design for the settings menu in the desktop app.

**Assets and Design Screens**
All assets and design screens have already been created.

- The Figma design can be found here https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=1%3A2
- The Assets required can be found here https://www.figma.com/file/gnhrfcg8OYvAz0zJXZz2r3/Atmosphere-Pro?node-id=0%3A1

For help with using Figma please watch this short tutorial video
https://user-images.githubusercontent.com/69275762/192322842-2ac40f88-c396-4a66-933b-3c8abae516c3.mov

**Additional context**
This work should be done on the UI_Redesign branch https://github.com/atsign-foundation/atmosphere_pro/tree/ui_redesign

### PR DESCRIPTION
**Pull request by AdiAr11**
**- What I did**
Implemented the Settings screen for desktop, closes #211 

**- How I did it**
I followed the figma design given and implemented it in flutter.

**- How to verify it**
Run the desktop app and from the left navigator, scroll down to the bottom and select settings. You'll see the settings page implemented with a little navigation bar changes as well.

### CODE REVIEW

**Comment by tinashe404** [comment]
@AdiAr11 hi, this looks good. @sachins-geekyants and @nitesh2599 please could you do a code review for this PR?

**Comment by nitesh2599** [comment]
@tinashe404 The code looks fine to me. But, there are some conflicts.

**Comment by AdiAr11** [comment]
@nitesh2599 I'll resolve the conflicts and push them.

**Comment by AdiAr11** [comment]
Hi @nitesh2599 , I have resolved the conflicts.

**Pull request merged**
