### PR TITLE
feat: sidebar fix

### PR DESCRIPTION
**Pull request by Sardar1208**
**- What I did - fixed the hight issue in side navigation
 - fixed issues with history screen and my files screen**

### CODE REVIEW

**Comment by sonle-geekyants** [comment]
@Sardar1208 I have faced this issue:
image

**Comment by Sardar1208** [comment]
> @Sardar1208 I have faced this issue: image

@sonle-geekyants Fixed this in recent update

**Comment by sonle-geekyants** [comment]
@Sardar1208 In the latest commit, there are still remaining some `Incorrect use of ParentDataWidget`.
Please fix it!

**Comment by Sardar1208** [comment]
> @Sardar1208 In the latest commit, there are still remaining some `Incorrect use of ParentDataWidget`. Please fix it!

@sonle-geekyants Fixed the issues

**Comment by sonle-geekyants** [comment]
@Sardar1208 Can you set borderRadius at the bottom of the sidebar to 0 to match with the Current atSign information card?
image

**Comment by Sardar1208** [comment]
> @Sardar1208 Can you set borderRadius at the bottom of the sidebar to 0 to match with the Current atSign information card? image

fixed

**Review by sonle-geekyants — APPROVED** [review]

**Pull request merged**
